plugins:
  cppcheck:
    enabled: true
    project: ScapeGameEngine.sln
    language: c++
    inconclusive: false
    checks:
      unusedFunction:
        enabled: false
      uninitMemberVar:
        enabled: false